### ISSUE TITLE
Looking for a good diagram.

### ISSUE THREAD

**Issue by prog20901** [r2dbc/r2dbc-pool#10]
It would be better if someone uploads a diagram to understand the difference between going for traditional JDBC vs R2DBC with a diagram as below

https://ejbvn.files.wordpress.com/2008/11/95.jpg

this one is easy to understand the connection pool

it would be great if many diagrams are created for easy understanding of core concepts - pooling difference, blocking vs non-blocking I/O RDBMS etc.,

**Comment by mp911de** [comment]
Please do not cross-post (see https://stackoverflow.com/questions/55988355/need-good-diagrams-core-concepts).
