### ISSUE TITLE
possible r2dbc-pool leak

### ISSUE THREAD

**Issue by climber73** [r2dbc/r2dbc-pool#102]
#### Versions

- Driver: r2dbc-postgreqsl
- Database: postgres
- Java: 11
- OS: macOS

#### Current Behavior

<details>
<summary>Stack trace</summary>

```
// your stack trace here
```

</details>
 
#### Table schema

<details>
<summary>Input Code</summary>

```sql
-- your SQL here;
```

</details>

#### Steps to reproduce

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Expected behavior/code

It looks like there is a subtle issue somewhere in r2dbc-pool, r2dbc-postgresql or even in projectreactor. [Here](https://github.com/climber73/r2dbc-pool-leak) is a small project to reproduce the issue. Please help with investigation of it. I understand that the test looks like a bit far-fetched, but it models our case we faced during development of billing application with CockroachDB as its database.

**Comment by climber73** [comment]
Here is short description of the issue:

As I mentioned before there is a simple project which is a HTTP server with one method [/payment](https://github.com/climber73/r2dbc-pool-leak/blob/main/src/main/java/sample/TestController.java#L35). When the server gets the payment request, it tries to execute 3 SQL queries (`select`, `update` and `insert`) inside a transaction in serializable level of isolation. The `update` query is likely going to be failed under heavy load because of 40001 error. The server is designed to retry such errors (10 times max).

Also that project has a [load test](https://github.com/climber73/r2dbc-pool-leak/blob/main/src/test/java/sample/AppTest.java), performing concurrent HTTP requests of the server. The test makes 2 phases: (1) preliminary phase - to assess needed time and (2) main phase where the same load test is run but for the half of the time (to get HTTP client close their connections). After the second phase the server never gets all DB connections idle in r2dbc connection pool. Some of them gets acquired forever (metric `r2dbc.pool.acquired` never gets 0 and that connections can't be used any more).

Because of that issue we had to switch to JDBC driver and now there are tons of threads which are blocked most of the time.

Kindly ask to help with that problem.

**Comment by mp911de** [comment]
It would make sense to reproduce the issue in an isolated environment. Debugging the pool through complex application logic is impossible for us.
