### ISSUE TITLE
Create new connection generates a lot of garbage

### ISSUE THREAD

**Issue by dstepanov** [r2dbc/r2dbc-pool#116]
I think this is the code that generates it:
https://github.com/r2dbc/r2dbc-pool/blob/1c54e515e151ca082b766713960197085ed3c8c5/src/main/java/io/r2dbc/pool/ConnectionPool.java#L120

<img width="1251" alt="obrazek" src="https://user-images.githubusercontent.com/666879/116439027-4bd11680-a80c-11eb-9e75-30396168f35f.png">

**Comment by mp911de** [comment]
Thanks for report. There are several occurrences of `String.format(…)` and I think we can precompute the name once and reuse it instead of running through the same code each time we create a connection.

**Comment by mp911de** [comment]
That's changed now.
