### ISSUE TITLE
Update documentation with correct pool construction

### ISSUE THREAD

**Issue by petromir** [r2dbc/r2dbc-pool#121]
@mp911de During investigation of stale idle connections in `reactor-pool`, Simon Baslé noted an interesting problem regarding ConnectionFactory and ConnectionPool construction (https://github.com/reactor/reactor-pool/issues/136#issuecomment-834263342).
In my opinion the documentation should be updated, so when people copy paste the examples they won't accidentally create 2 pools instead of one, as this results in 10 always open connections.

**Comment by mp911de** [comment]
You mean configuring `ConnectionPool` with `ConnectionFactories.get(ConnectionFactoryOptions.builder().option(DRIVER, "pool").option(PROTOCOL, "postgresql")…)`?

Do you have a suggestion? `ConnectionFactories.get(…)` is part of the SPI and can only return `ConnectionFactory` and not `ConnectionPool`.

**Comment by mp911de** [comment]
But isn't that basically what we already have:

> **Programmatic Configuration**
> 
> ```java
> ConnectionFactory connectionFactory = …;
> 
> ConnectionPoolConfiguration configuration = ConnectionPoolConfiguration.builder(connectionFactory)
>    .maxIdleTime(Duration.ofMillis(1000))
>    .maxSize(20)
>    .build();
> 
> ConnectionPool pool = new ConnectionPool(configuration);
>  
> 
> Mono<Connection> connectionMono = pool.create();
> 
> // later
> 
> Connection connection = …;
> Mono<Void> release = connection.close(); // released the connection back to the pool
> 
> // application shutdown
> pool.dispose();
> ```

I think we can add a bit of comment to folks willing to read the docs to outline what `connectionFactory` actually represents.

**Comment by petromir** [comment]
Thanks!
