### ISSUE TITLE
Please make registerJmx and pool name externally configurable for Spring Boot

### ISSUE THREAD

**Issue by amoffet** [r2dbc/r2dbc-pool#122]
Versions

Driver: PostgreSQL 0.8.7.RELEASE
Database: PostgreSQL 11
Java: 8
OS: OSX
Current Behavior

registerJmx, along with the name of the pool, should be externally configurable in R2dbcProperties.Pool through R2dbcAutoConfiguration.

Expected behavior/code

I would like to be able to be configured registerJmx and the pool name  externally if I am using Spring Boot

**Comment by mp911de** [comment]
That issue was fixed with #113.
