### ISSUE TITLE
Default maxLifeTime value result in immediate eviction of all connections

### ISSUE THREAD

**Issue by bezmax** [r2dbc/r2dbc-pool#129]
## Bug Report

The default for maxLifeTime is [defined](https://github.com/r2dbc/r2dbc-pool/blob/main/src/main/java/io/r2dbc/pool/ConnectionPoolConfiguration.java#L47) as `NO_TIMEOUT = Duration.ofNanos(-1)`, which is supposed to mean "No timeout". However, the [current implementation of actual evectionPredicate](https://github.com/r2dbc/r2dbc-pool/blob/main/src/main/java/io/r2dbc/pool/ConnectionPool.java#L191-L196), attempts to do `toMillis` conversion, which results in `0`, thus resulting in the `if (maxIdleTimeMills == 0 || maxLifeTimeMillis == 0)` always returning `true`.

#### Possible Solution

Replace `maxLifeTimeMillis == 0` with `maxLifeTime.isZero()`.

**Comment by mp911de** [comment]
Care to submit a pull request to fix the problem?

**Comment by bezmax** [comment]
Sure, will do!

**Comment by GabrielCalin** [comment]
Just a friendly ping, could someone merge [PR](https://github.com/r2dbc/r2dbc-pool/pull/155)?
The fact is that this is a major bug at the moment, as the pool behaves poorly when `maxLifeTime` is not explicitly set.

**Comment by Inego** [comment]
Current workaround: set `spring.r2dbc.pool.max-life-time` to -1.
