### ISSUE TITLE
Wrong information in README.md

### ISSUE THREAD

**Issue by frombrest** [r2dbc/r2dbc-pool#130]
In README.md we have table with description of ConnectionPoolConfiguration options.

- maxLifeTime
- maxAcquireTime
- maxCreateConnectionTime

Has such phrase in description: ```Negative values indicate no timeout```

At the same time 
ConnectionPoolConfiguration.Builder has checks for that values and they could not be _null_, or _negative_
Ex:
```
    public ConnectionPoolConfiguration.Builder maxIdleTime(Duration maxIdleTime) {
        Assert.requireNonNull(maxIdleTime, "maxIdleTime must not be null");
        if (maxIdleTime.isNegative()) {
            throw new IllegalArgumentException("maxIdleTime must not be negative");
        } else {
        // . . . 
```

Do we need to correct they to ```Zero (PT0S) values indicate no timeout``` ?

**Comment by mp911de** [comment]
What you see is a difference between `0.8.x` ([`0.8.x` branch](https://github.com/r2dbc/r2dbc-pool/tree/0.8.x#getting-started)) and `0.9.x` ([`main` branch](https://github.com/r2dbc/r2dbc-pool/tree/main#getting-started)). We changed the no timeout/zero-timeout behavior with #77 for the `0.9.x` development line.
