### ISSUE TITLE
Support configuration of minimum idle connections

### ISSUE THREAD

**Issue by mostafavahidi** [r2dbc/r2dbc-pool#141]
Hi all,

Recently, my team has come across an issue where number of connections in the connection pool drops to 0 after some time that the pool is not used.
We want to be able to set some property in r2dbc-pool that allows us to keep a minimum number of idle connections regardless of the usage of the pool.

After some searching, I found that the apache DBCP library offers minIdle setting:
https://commons.apache.org/proper/commons-dbcp/configuration.html
minIdle: The minimum number of connections that can remain idle in the pool, without extra ones being created, or zero to create none.

Unfortunately, in r2dbc-pool, I haven't found a similar param. The following two params are similar but look like they would  change the lifecycle behavior of the pool itself:
backgroundEvictionInterval & maxIdleTime

They're not quite what we're after. Is there a solution/hack that I can do that will allow me to set the minimum number of idle connections I want to keep at all times that I am missing?

If not, are there any plans that this will be added in the future?

Thank you for response,
Mostafa

**Comment by mp911de** [comment]
That's in place now. InitialSize is somewhat overlapping, if both values are configured, we're going to use the greater one.

**Comment by grantas33** [comment]
Currently, after `maxIdleTime` has passed all idle connections close and `minIdle` field does not have any effect. Is this a bug or expected behavior? I would expect that at least `minIdle` number of connections should never be closed.
