### ISSUE TITLE
allow inheritance from abstract @MappedSuperClass in child entity

### ISSUE THREAD

**Issue by cforce** [r2dbc/r2dbc-pool#145]
I would like to reuse basic entity properties with DRY as known by JPA
I could not get it working as well did not found any doc it is (not) supported

```
public class Student extends BaseEntity{
 String name;
}

@MappedSuperclass
public abstract class BaseEntity {
    @Id
    @GeneratedValue
    Long id;

    @CreatedDate
    LocalDateTime createdAt;
    @LastModifiedDate
    LocalDateTime updatedAt;
}
```

**Comment by mp911de** [comment]
This is neither JPA nor a mapping framework, this project keeps track of issues for the R2DBC connection pool.
