### ISSUE TITLE
Confused by document: Why “Creates a ConnectionPool wrapping an underlying ConnectionFactory” comment appear with `ConnectionFactory` creations?

### ISSUE THREAD

**Issue by Jason5Lee** [r2dbc/r2dbc-pool#146]
Does it actually mean “Creates a ConnectionFactory wrapping an underlying ConnectionPool”?

**Comment by Jason5Lee** [comment]
Sorry my English is bad.

**Comment by mp911de** [comment]
No, it means what it says: `ConnectionFactories.get("r2dbc:pool:<my-driver>:…)` asks the `pool` (Connection Pool) to configure a `my-driver` `ConnectionFactory` and then the pool uses `my-driver` to obtain connections from.

**Comment by Jason5Lee** [comment]
If I create a connection from the connection factory created from the `get` method, is it from the pool?

**Comment by mp911de** [comment]
Yes, it's a pooled one.
