### ISSUE TITLE
Connection unexpectedly closed

### ISSUE THREAD

**Issue by menakaprabu** [r2dbc/r2dbc-pool#153]
I am using r2dbc-pool (0.8.8.RELEASE) where I am getting Connection unexpectedly closed exception for every 30 mins from application launch time. It is not happening without using pool. I am using mssql protocol. Please suggest, what I am missing here.

**Comment by mp911de** [comment]
The pool has a default max idle time of 30 minutes. If you configure `Duration.ZERO` then background disposal is disabled. Please note that in version 0.9 the behavior was changed. To disable background disposal, with version 0.9 you need to configure a negative timeout such as `-1`.

**Comment by menakaprabu** [comment]
Thanks, Mark for the quick response.
I have a question on how creating the pool.
I see both with driver as pool and without as well.
Which is the correct one?

ConnectionFactory pooledConnectionFactory =
ConnectionFactories.get(ConnectionFactoryOptions.builder()
        .option(DRIVER,"pool")
        .option(PROTOCOL,"postgresql") // driver identifier, PROTOCOL
is delegated as DRIVER by the pool.
        .option(HOST,"…")
        .option(PORT,"…")
        .option(USER,"…")
        .option(PASSWORD,"…")
        .option(DATABASE,"…")
        .build()

OR

ConnectionFactory connectionFactory =
ConnectionFactories.get(ConnectionFactoryOptions.builder()
        .option(DRIVER,"postgresql")
        .option(HOST,"…")
        .option(PORT,"…")
        .option(USER,"…")
        .option(PASSWORD,"…")
        .option(DATABASE,"…")
        .build());

// Create a ConnectionPool for connectionFactory
ConnectionPoolConfiguration configuration =
ConnectionPoolConfiguration.builder(connectionFactory)
        .maxIdleTime(Duration.ofMillis(1000))
        .maxSize(20)
        .build();

Thanks!
