### ISSUE TITLE
Soft eviction for in-use connections

### ISSUE THREAD

**Issue by nihsmik** [r2dbc/r2dbc-pool#157]
## Motivation
In-use connections are immediately disposed of when the max lifetime is over.
I expect not to cancel any active requests even if the connection evicts.

## Desired solution

How about just marking evict to lifetime over connections like HikariCP?
There is no problem evicting idle connections immediately.
I suggest soft-evicting the other connections that are in use.
The soft evicted connection becomes idle and then closed in the background.

## Additional context
[HikariCP markEvicted](https://www.tabnine.com/code/java/methods/com.zaxxer.hikari.pool.PoolEntry/markEvicted)

**Comment by mp911de** [comment]
Related to https://github.com/reactor/reactor-pool/issues/157, I think we need to make sure this is possible with Reactor Pool as the underlying object pool.

**Comment by mp911de** [comment]
Closing since the related upstream issue was closed. Without a change in Reactor Pool, we're not able to provide such a feature.
