### ISSUE TITLE
Question: Release version of 1.0.0.RC1

### ISSUE THREAD

**Issue by htejwani** [r2dbc/r2dbc-pool#179]
Since oracle recommends using 1.0.0.RELEASE version of the SPI and your RC1 version uses that, when can we expect a release version from your end?

**Comment by mp911de** [comment]
R2DBC Pool is built on top of Reactor Pool, so we can ship a 1.0 GA Release once Reactor Pool 1.0 (and Project Reactor 3.5) go GA. I expect that to happen in 2-3 Months max.

In any case, R2DBC Pool 1.0 RC1 already uses R2DBC SPI 1.0.0.RELEASE and we don't expect many changes until GA.

**Comment by htejwani** [comment]
Ok, thankyou very much for your prompt reply.
