### ISSUE TITLE
Should BACKGROUND_EVICTION_INTERVAL be of type Option<Duration>

### ISSUE THREAD

**Issue by duyleekun** [r2dbc/r2dbc-pool#180]
https://github.com/r2dbc/r2dbc-pool/blob/dae00e57f5509a7fea769df6ea116fd85a4c990b/src/main/java/io/r2dbc/pool/PoolingConnectionFactoryProvider.java#L60

I'm unable to set `BACKGROUND_EVICTION_INTERVAL` via `ConnectionFactoryOptions.builder().option(PoolingConnectionFactoryProvider.BACKGROUND_EVICTION_INTERVAL,XXXX)`

Seem like `XXXX` can only be Integer and internally, it requires it to be either `String` or `Duration`. Am I missing something?

**Comment by mp911de** [comment]
Good catch, do you want to submit a pull request to fix that issue?
