### ISSUE TITLE
Question: Load balancing and failover attributes in connection string 

### ISSUE THREAD

**Issue by htejwani** [r2dbc/r2dbc-pool#182]
How do we form a connection string in r2dbc pool for Oracle to specify load balancing and failover with multiple hosts. Her's the jdbc connection string sample:
jdbc:oracle:thin:@(DESCRIPTION=FAILOVER=ON)(LOAD_BALANCE=ON)(ADDRESS_LIST=(ADDRESS=.....))

**Comment by htejwani** [comment]
Hello, can someone please comment on this? Please let me know if the question isn't clear

**Comment by mp911de** [comment]
The connection pool does not implement any kind of load balancing, it's always the driver.
