### ISSUE TITLE
io.r2dbc.spi.Result.getRowsUpdated

### ISSUE THREAD

**Issue by Lovecxgood** [r2dbc/r2dbc-pool#185]
io.r2dbc.spi.Result.getRowsUpdated  can not  return  a affected num   in  version  1.0.0.RELEASE  no signal was emited like onerror  oncompleted  onnext
version 0.9.2.RELEASE  is ok

 
				public void onNext(Result t) {
					t.getRowsUpdated().subscribe(new TSubscriber<Long>() {
						@Override
						public void onSubscribe(Subscription s) {
							s.request(1);
						}

						@Override
						public void onNext(Long t) {
							num = t.intValue();
						}
					});
				}

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
