### ISSUE TITLE
Add io.r2dbc.pool.ConnectionPool.toString

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-pool#20]
We should add a meaningful `toString()` method to `io.r2dbc.pool.ConnectionPool` to expose useful debug information such as the driver name.

**Comment by ttddyy** [comment]
One way we could do is just delegate to driver's `ConnectionFactory#toString()` to show the information.
For `toString` implementation in pool, it would be something like this:

```java
@Override
public String toString() {
    return "ConnectionPool{" +
        "factory=" + factory +
        ", connectionPool=" + connectionPool +
        // skipping "maxAcquireTime" and "destroyHandlers" instance variable
        '}';
}
```

For postgres, `PostgresqlConnectionFactory#toString()` shows:

```
PostgresqlConnectionFactory{clientFactory=MonoJust, configuration=PostgresqlConnectionConfiguration{applicationName='test-application-name', connectTimeout=null, database='test-database', forceBinary='false', host='test-host', password='test-password', port=5432, schema='null', username='test-username'}}
```

For H2, `H2ConnectionFactory#toString()` shows:

```
H2ConnectionFactory{clientFactory=MonoDefer}
```
H2 currently doesn't show `configuration`. We could ask to show the configuration as well.

Or, simply it can show just `ConnectionFactory` class name: `factory.getClass().getName()`
