### ISSUE TITLE
Cannot unwrap a PooledConnection as the class is package protected

### ISSUE THREAD

**Issue by gpaglia** [r2dbc/r2dbc-pool#201]
## Bug Report

PooledConnection should be public or some other ways of unwrapping a PooledConnection to get the underlying technology-specific connection should be provided.

For example, if PooledConnection wraps a PostgresqlConnection, one needs to unwrap the PooledConnection to get the PostgresqlConnection to execute postgres-specific operations like LISTEN and NOTIFY.

In the documentation I dind't find any hints on how to resolve.

#### Versions

- Driver:: 1.0.1.RELEASE
- Database: postgres 16
- Java: 17
- OS: Windows 10

#### Current Behavior

To work around this, I created a public utility class in the io.r2dbc.pool package with a public method tht  calls the PooledConnection#unwrap method.

**Comment by mp911de** [comment]
That shouldn't be necessary when calling `Wrapped.unwrap(PostgresqlConnection.class)`. The unwrapping mechanism will unwrap the inner wrapped elements until it can return `PostgresqlConnection`.

**Comment by gpaglia** [comment]
Thanks, will try it.
