### ISSUE TITLE
Connection pool size

### ISSUE THREAD

**Issue by msoub** [r2dbc/r2dbc-pool#34]
We are using `r2dbc-pool` along with `r2dbc-postgresql` and despite setting the `maxSize` of the pool configuration, it looks like it's not respected.

Here is the config inheriting from `AbstractR2dbcConfiguration`:
```
    @Bean
    override fun connectionFactory(): ConnectionFactory {
        val connectionFactory = ConnectionFactories.get(builder()
            .option(DRIVER, "postgresql")
            .option(HOST, host)
            .option(PORT, port)
            .option(USER, username)
            .option(PASSWORD, password)
            .option(DATABASE, database)
            .build())

        val configuration = ConnectionPoolConfiguration.builder(connectionFactory)
            .initialSize(1)
            .maxSize(1)
            .registerJmx(false)
            .build()

        return ConnectionPool(configuration)
    }
```

**Comment by mp911de** [comment]
Can you please retest with `0.8.0.BUILD-SNAPSHOT` and report whether the issue still persists?

**Comment by msoub** [comment]
Yes, I do confirm it's still there.

**Comment by mp911de** [comment]
I wasn't able to reproduce the issue using the following code:

```java
ConnectionPoolConfiguration configuration = ConnectionPoolConfiguration.builder(connectionFactory)
    .initialSize(1)
    .maxSize(1)
    .name("foo")
    .registerJmx(true)
    .build();

ConnectionPool pool = new ConnectionPool(configuration);

pool.create().block();
pool.create().block();
```

Maybe you could elaborate on how to reproduce (ideally attach a bit of code) the issue.

**Comment by msoub** [comment]
The problem came from the Hikari pool used by Flyway to ensure our db migration. Sorry about that.

BTW, is there any plan to have re-use R2DBC to achieve db migration?

**Comment by mp911de** [comment]
Flyway is developed by RedGate. Can you please file a ticket in Flyway's issue tracker at https://github.com/flyway/flyway/issues?

There was already a discussion on Twitter: https://twitter.com/Julia_Hayward/status/1161225914790944768

With sufficient interest, these things may happen.

**Comment by msoub** [comment]
Thanks for the suggestion. Here is the [ticket](https://github.com/flyway/flyway/issues/2502).
