### ISSUE TITLE
Using Duration.ZERO for no timeout (or infinite timeout) is confusing

### ISSUE THREAD

**Issue by snicoll** [r2dbc/r2dbc-pool#77]
Using `r2dbc-pool` `0.8.3.RELEASE`, there are a number of timeout-related properties that have a `Duration.ZERO` as their default to indicate the absence of a timeout. 

Concretely, this means `0ms` which reads funny if you try to expose those settings as configuration properties, see https://github.com/spring-projects/spring-boot/pull/21219

The following are affected:

* `maxCreateConnectionTime` if the timeout to create a connection is `0ms`, I read it as it should throw an exception if the creation is not immediate
* `maxAcquireTime` if the timeout to acquire a connection from the pool is `0ms`, I read it as it should throw an exception if the retrieval of the connection is not immediate
* `maxLifeTime` is even weirder. With the default of `0ms` I read it as the connection should be removed from the pool as soon as it's created.

I think that either the default should be `null`. A `null` duration conveys better the absence of a timeout than a value of 0. If you don't want that, an alternative would be to use a negative value. While unusual for a duration, using `-1` is quite common.

**Comment by mp911de** [comment]
For now, we're tied to zero as an infinite timeout. Probably there are cases where a pool helps with resiliency in the sense that connections get verified and closed after use (for `maxLifeTime=0ms`).

We should consider for R2DBC Pool 0.9 switching to negative values to indicate infinite timeouts to not clash with zero values.
