### ISSUE TITLE
Can you improve the documentation

### ISSUE THREAD

**Issue by Lovecxgood** [r2dbc/r2dbc-pool#79]
Can you improve the documentation plz？？？？？？？？？？？？？？？？？

**Comment by mp911de** [comment]
Thanks for reaching out. Let us know what you’re looking for so we can document those bits.

**Comment by Lovecxgood** [comment]
aha!!!  your documents is too simple to understand,  maybe  you can put some  CURD samples or some more detail codes.
for example Connection connection = …;  I can not to know how can I get this connection  from~
thanks!!

**Comment by mp911de** [comment]
This project handles connection pooling and is responsible for resource management. Our [readme](https://github.com/r2dbc/r2dbc-pool/blob/main/README.md#getting-started) contains a getting started guide that explains how to obtain and how to release connections. 

If you're looking for an introduction to how to get started with particular drivers, then take a look at the individual drivers, e.g. [Postgres](https://github.com/pgjdbc/r2dbc-postgresql).

Let us know if there's anything else we can help with or whether we may close this ticket.

**Comment by Lovecxgood** [comment]
thanks
