### ISSUE TITLE
Too many reconnection retries with r2dbc + pool + r2dbc-postgres

### ISSUE THREAD

**Issue by DRSains** [r2dbc/r2dbc-pool#80]
- Driver: io.r2dbc:r2dbc-postgresql:0.8.2.RELEASE and r2dbc-pool:0.8.2.RELEASE
- Database: POSTGRES
- Java: 11
- OS: Linux

#### Current Behavior

Because of a Vault error, credentials generated for Postgres will be wrong. What happens is that the application will try thousands of times to reconnect to the DB, filling the DB logs. I don't know by what component this is cause, this happened several days ago and I don't have full logs. What I have is just this stacktrace (only for the http part):

```
i.r.p.ExceptionFactory$PostgresqlAuthenticationFailure: password authentication failed for user \"v-approle-readwrit-3524s732v0xv72tqv0vx-1595235650\"\n\tat i.r.p.ExceptionFactory.createException(ExceptionFactory.java:74)\n\tat i.r.p.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:110)\n\tat r.c.p.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96)\n\tat r.c.p.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:319)\n\tat r.c.p.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)\n\tat r.c.p.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)\n\tat r.c.p.FluxCreate$SerializedSink.next(FluxCreate.java:153)\n\tat i.r.p.c.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:679)\n\tat i.r.p.c.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:867)\n\tat i.r.p.c.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:801)\n\tat i.r.p.c.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:710)\n\tat r.c.p.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)\n\tat r.c.p.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:845)\n\tat r.c.p.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)\n\tat r.c.p.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)\n\tat r.n.c.FluxReceive.drainReceiver(FluxReceive.java:218)\n\tat r.n.c.FluxReceive.onInboundNext(FluxReceive.java:351)\n\tat r.n.c.ChannelOperations.onInboundNext(ChannelOperations.java:348)\n\tat r.n.c.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat i.n.h.c.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)\n\tat i.n.h.c.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(Abstract...
```

the result of continous retries was to fill up RDS instances disks with the Logs. 

I had a peek in the code but can't really find the issue, would be great to have some help.

config is:
```java
    public ConnectionFactory connectionFactory() {
        var postgresqlConnectionConfiguration = getPostgresConfiguration();

        var postgresqlConnectionFactory = new PostgresqlConnectionFactory(postgresqlConnectionConfiguration);

        var poolFactoryConfiguration = ConnectionPoolConfiguration.builder(postgresqlConnectionFactory)
                .maxIdleTime(Duration.ofMillis(1000))
                .maxSize(20)
                .build();
        var pooledConnectionFactory = new ConnectionPool(poolFactoryConfiguration);
        return pooledConnectionFactory;
    }

    protected PostgresqlConnectionConfiguration getPostgresConfiguration() {
        return PostgresqlConnectionConfiguration.builder()
                .host(dbProperties.getHost())
                .port(dbProperties.getPort())
                .username(dbProperties.getUsername())
                .password(dbProperties.getPassword())
                .database(dbProperties.getDatabase())
                .build();
    }

**Comment by mp911de** [comment]
See also https://gitter.im/R2DBC/r2dbc?at=5f22c8fec1c0090e64b0f174.

**Comment by mp911de** [comment]
`ConnectionPoolConfiguration` defaults to an initial size of `10` connections. Upon the first connection acquisition (`ConnectionPool.create()`), all connections are pre-initialized. If all connections fail due to connectivity/authentication issues, the underlying driver sees `11` connection attempts (`10` initial connections plus a retry for `create(…)`).

By enabling the debug log for `io.r2dbc`, you can observe the message exchange between client and server and see how many authentication attempts happened.

However, each subsequent attempt to obtain the connection will attempt to initialize the idle connections again and that is why each connection acquisition will result in 10+ connection attempts.

I think the only way out here is to reduce the initial connection count to zero. We also should ask `reactor-pool` whether there's something else we can do here.

Paging @simonbasle.

**Comment by dariodariodario** [comment]
That could actually be a satisfying solution. I will try this for sure. Thanks for that!

**Comment by simonbasle** [comment]
I think your analysis is correct @mp911de. the pool tries to enforce the minimum size by warming up each time there is an attempt at acquiring which detects the pool is undersized.

**Comment by mp911de** [comment]
I'd close this ticket now unless there's an objection to keeping it open.
