### ISSUE TITLE
Allow enabling JMX via PoolingConnectionFactoryProvider

### ISSUE THREAD

**Issue by dandew** [r2dbc/r2dbc-pool#83]
#### Is your feature request related to a problem? Please describe

It's not possible to set the `registerJmx` to `true` via `PoolingConnectionFactoryProvider`.

#### Describe the solution you'd like

- Add a new `Boolean` `REGISTER_JMX` `Option`
- Use it say below this line https://github.com/r2dbc/r2dbc-pool/blob/main/src/main/java/io/r2dbc/pool/PoolingConnectionFactoryProvider.java#L151

#### Describe alternatives you've considered

None.

#### Teachability, Documentation, Adoption, Migration Strategy

This is backwards compatible and should not affect existing users: if the option is not used, it's just going to be ignored.

**Comment by mp911de** [comment]
Great proposal. Do you want to submit a pull request?

**Comment by tginsberg** [comment]
I would like to give this a try if the original submitter is not going to.

**Comment by mp911de** [comment]
Feel free, the last activity is from a month ago.
