### ISSUE TITLE
Gracefully fail when new connection can't be opened

### ISSUE THREAD

**Issue by simontb** [r2dbc/r2dbc-pool#9]
When a new connection can't be opened because maximum number of connections has been aquired, it would be nice if it was possible to configure the pool to wait for a connection to be freed up instead of failing with an exception.

**Comment by mp911de** [comment]
We're using Reactor Pool as backing pool implementation. That would be something the backing pool has to provide. On our side, we could add timed retries but I'm not sure that's efficient.

/cc @simonbasle @bsideup

**Comment by simonbasle** [comment]
The `reactor-pool` should do just what you are describing (unless I misunderstood something):

 1. try to `acquire()` a resource (ie. a connection)
 2. the pool checks if an idle resource is available, and if so emits it
 3. the pool checks if the `allocationStrategy` gives a "permit" to allocate a new resource, and if so invokes the allocator `Publisher` and emits the created resource
 4. the pool places the acquire `Mono` `Subscription` in a pending queue and waits for a `release()` to occur before it can retry to serve it

Additionally, one feature that is IIRC used by r2dbc-pool is the pending queue limit: past a number of pending `acquire`, further attempts at calling `acquire()` are failed fast.

**Comment by simontb** [comment]
@simonbasle I am looking for a slightly different behavior. That when an error occurs in the third step you described, the exception is caught and the pool waits for a resource to become released and emits it. The example in context of r2dbc-pool is `org.postgresql.util.PSQLException: FATAL: sorry, too many clients already`. When this exception occurs, the limit of db connections has been reached, but the pool could recover by waiting for an existing connection to become idle.

Currently `AllocationStrategy` only defines whether a new resource can be created, but not what should happen when creating fails. Currently, I can imagine 3 strategies:

- Fail-hard: The current behavior
- Fail-soft: The behavior I described
- Fail-transparently: Let the subscriber descide what to do. Either by calling a method on the pool before aquiring, or by catching the exception and then call something like `aquireLazy()` that will never attempt to create a new resource.

Not sure if the latter is needed for my use-case though.

**Comment by mp911de** [comment]
If the pool is not exhausted (case of `FATAL: sorry, too many clients already`), then we have no other option than to fail. The contract is to allocate a new connection if the pool is not exhausted. An attempt fails and so the pool propagates the exception.

Do you have an example of a JDBC pool that behaves the way you described?

**Comment by mp911de** [comment]
r2dbc/r2dbc-pool#43 introduced retry configuration that addressed the issue.
